apiVersion: skaffold/v1beta15
kind: Config
build:
  artifacts:
    - image: quay.io/owensengoku/leeroy-web
      context: ./leeroy-web/
    - image: quay.io/owensengoku/leeroy-app
      context: ./leeroy-app/
  tagPolicy:
      sha256: {}
deploy:
  kubectl:
    manifests:
      - ./leeroy-web/kubernetes/*
      - ./leeroy-app/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    namespace: default
    port: 8080
    localPort: 9000
